### ISSUE TITLE
Babel-transpile issues when using vuegister in combination with this plugin

### ISSUE THREAD

**Issue by jsproede** [iatsiuk/vuegister-plugin-babel#12]
Hi,

currently I’m developing a small Visual Studio Code plugin which runs mocha tests directly inside VS Code.

My next step was to run unit-tests which imports .vue-files. So I installed your npm-package vuegister, which extracted the JavaScript inside my .vue-files without any issues.
But when using newer ECMAScript language inside my .vue-files, I want to let Babel transpile the script before running the tests. As I understand, your vuegister-plugin-babel does exactly what I want. But after I installed the npm package, I didn’t really understood how to use your plugin.

I debugged vuegister a bit and experienced, that the plugin contains a `transpile`-method, but the parameter `lang` only contains `html` or `js`. So the babel-plugin never gets required.

I fixed the issue by naming the plugin folder to 'vuegister-plugin-js'. Afterwards vuegister passes the script to Babel (via the plugin), which transpiles the code and my tests are finally working.

I doubt that this is the correct usage of vuegister and vuegister-plugin-babel.

Could you explain a bit more, how to use vuegister in combination with vuegister-plugin-babel?

Thank you very much.

**Comment by iatsiuk** [comment]
Hi,

just use [this api call](https://github.com/iatsiuk/vuegister/blob/master/api.md#registeroptions--boolean-) to reassign default language for script tag.

for example this is `register-babel.js` file:
```js
require('vuegister').register({ lang: { script: 'babel'	} });
```

now you can require it like this and use any es6/babel syntax:
```js
npx mocha -r jsdom-global/register -r ./register-babel.js
```

**Comment by jsproede** [comment]
Hi,

great. It's working now without renaming the folder of the plugin inside my node_modules folder.

Thank you very much for your help!
